// data.js
// Recetas normalizadas + separación en "antes de hornear" (preBake) y "después de hornear" (postBake).
// Unificaciones aplicadas: salsa de tomate, mozzarella, champiñón, pepperoni, panceta, carne de vacuno, etc.
// Parmigiano/Parmesano -> "Parmesano" (simplificado para uso personal).

window.RECIPES = [
  {
    id: "5-formaggi",
    type: "pizza",
    name: "5 Formaggi",
    image: "img/5-formaggi.png",
    preBake: ["Mozzarella", "Queso de cabra"],
    postBake: ["Queso gorgonzola", "Almendras laminadas", "Parmesano"],
  },
  {
    id: "la-nostra-margherita",
    type: "pizza",
    name: "La Nostra Margherita",
    image: "img/la-nostra-margherita.jpg",
    preBake: ["Salsa de tomate", "Mozzarella"],
    postBake: ["Mozzarella de búfala", "Albahaca fresca", "Aceite de oliva"],
  },
  {
    id: "prosciutto",
    type: "pizza",
    name: "Prosciutto",
    image: "img/prosciutto.png",
    preBake: ["Salsa de tomate", "Mozzarella", "Jamón york"],
    postBake: ["Orégano fresco"],
  },
  {
    id: "piemontese",
    type: "pizza",
    name: "Piemontese",
    image: "img/piemontese.png",
    preBake: ["Salsa de tomate", "Mozzarella", "Cebolla caramelizada", "Aceituna taggiasca", "Panceta"],
    postBake: ["Orégano fresco"],
  },
  {
    id: "pepperoni",
    type: "pizza",
    name: "Pepperoni",
    image: "img/pepperoni.png",
    preBake: ["Salsa de tomate", "Mozzarella", "Pepperoni"],
    postBake: [],
  },
  {
    id: "prosciutto-e-funghi",
    type: "pizza",
    name: "Prosciutto e Funghi",
    image: "img/prosciutto-e-funghi.png",
    preBake: ["Salsa de tomate", "Mozzarella", "Jamón york", "Champiñón"],
    postBake: ["Orégano fresco", "Pimienta negra"],
  },
  {
    id: "panceta-e-funghi",
    type: "pizza",
    name: "Panceta e Funghi",
    image: "img/panceta-e-funghi.jpg",
    preBake: ["Salsa de tomate", "Mozzarella", "Panceta", "Champiñón"],
    postBake: ["Orégano"],
  },
  {
    id: "pepperoni-e-bolognese",
    type: "pizza",
    name: "Pepperoni e Bolognese",
    image: "img/pepperoni-e-bolognese.jpg",
    preBake: ["Salsa boloñesa", "Mozzarella", "Pepperoni"],
    postBake: ["Orégano"],
  },
  {
    id: "jamon-york-y-ricotta",
    type: "pizza",
    name: "Jamón York y Ricotta",
    image: "img/jamon-york-ricotta.jpg",
    preBake: ["Salsa de tomate", "Mozzarella", "Jamón york"],
    postBake: ["Ricotta", "Albahaca"],
  },
  {
    id: "berenjena-y-queso-de-cabra",
    type: "pizza",
    name: "Berenjena y Queso de Cabra",
    image: "img/berenjena-queso-cabra-2.jpg",
    preBake: ["Salsa de tomate", "Mozzarella", "Berenjena", "Cebolla caramelizada", "Queso de cabra"],
    postBake: [],
  },
  {
    id: "diavola-napoletana",
    type: "pizza",
    name: "Diavola Napoletana",
    image: "img/diavola-napolitana.jpg",
    preBake: ["Salsa de tomate", "Mozzarella", "Pollo marinado", "Pepperoni", "Carne de vacuno", "Champiñón"],
    postBake: ["Hojilla picante", "Parmesano"],
  },
  {
    id: "vulcano-bolognese",
    type: "pizza",
    name: "Vulcano Bolognese",
    image: "img/vulcano-bolognese.jpg",
    preBake: ["Salsa boloñesa", "Salsa de tomate", "Scamorza ahumada rallada", "Panceta", "Pepperoni", "Salchicha toscana"],
    postBake: ["Albahaca fresca"],
  },
  {
    id: "vulcano-formaggi",
    type: "pizza",
    name: "Vulcano Formaggi",
    image: "img/vulano-formaggi.jpg",
    preBake: ["Masa napolitana", "Crema de parmesano", "Mozzarella", "Salsa de tomate", "Panceta con cebolleta al vinagre de Módena"],
    postBake: ["Orégano"],
  },
  {
    id: "mortadella-tartufata",
    type: "pizza",
    name: "Mortadella Tartufata",
    image: "img/mortadella-tartufata.jpg",
    preBake: ["Salsa de tomate", "Mozzarella", "Mortadela trufada", "Mozzarella de búfala", "Salsa pesto", "Polvo de pistacho", "Salsa de trufa"],
    postBake: [],
  },
  {
    id: "carbonara-tartufata",
    type: "pizza",
    name: "Carbonara Tartufata",
    image: "img/carbonara-tartufata.jpg",
    preBake: ["Salsa blanca tartufata", "Mozzarella", "Cebolla roja", "Champiñón", "Huevo a baja temperatura", "Panceta"],
    postBake: ["Pimienta negra", "Parmesano"],
  },
  {
    id: "vitella-e-pancetta",
    type: "pizza",
    name: "Vitella e Pancetta",
    image: "img/vitella-pancetta.jpg",
    preBake: ["Salsa de tomate", "Mozzarella", "Carne de vacuno", "Panceta"],
    postBake: ["Tomate rosa", "Ajetes", "Aceituna taggiasca", "Albahaca fresca"],
  },
  {
    id: "verdure-e-formaggio-di-capra",
    type: "pizza",
    name: "Verdure e Formaggio di Capra",
    image: "img/verdure-formaggio-capra.jpg",
    preBake: ["Salsa de tomate", "Mozzarella", "Calabacín asado", "Berenjena asada", "Pimiento rojo asado"],
    postBake: ["Tomate semiseco", "Queso de cabra", "Albahaca fresca", "Salsa pesto"],
  },
  {
    id: "pollo-barbecue",
    type: "pizza",
    name: "Pollo Barbecue",
    image: "img/pollo-barbecue.jpg",
    preBake: ["Salsa barbacoa", "Mozzarella", "Queso scamorza", "Cebolla roja", "Pollo marinado"],
    postBake: ["Orégano fresco"],
  },
  {
    id: "serrana",
    type: "pizza",
    name: "Serrana",
    image: "img/serrana.jpg",
    preBake: ["Salsa de tomate", "Mozzarella", "Pimiento rojo asado", "Pimiento verde asado", "Romero"],
    postBake: ["Paleta ibérica", "Aceite de oliva"],
  },
  {
    id: "filippo",
    type: "pizza",
    name: "Filippo",
    image: "img/filippo.jpg",
    preBake: ["Salsa de tomate", "Mozzarella", "Hojilla picante", "Cebolla morada", "Salame finocchiona"],
    postBake: ["Peperoncino rojo", "Perejil", "Miel"],
  },
  {
    id: "gricia",
    type: "pizza",
    name: "Gricia",
    image: "img/gricia.jpg",
    preBake: ["Salsa blanca", "Mozzarella", "Panceta", "Cebolla caramelizada"],
    postBake: ["Queso manchego", "Perejil", "Pimienta negra"],
  },
  {
    id: "chorizo-e-uovo",
    type: "pizza",
    name: "Chorizo e Uovo",
    image: "img/chorizo-e-uovo.jpg",
    preBake: ["Salsa de tomate", "Mozzarella", "Chorizo"],
    postBake: ["Huevo a baja temperatura", "Perejil"],
  },
  {
    id: "gorgonzola-e-pera",
    type: "pizza",
    name: "Gorgonzola e Pera",
    image: "img/gorgonzola-e-pera.jpg",
    preBake: ["Salsa blanca", "Mozzarella", "Pera", "Queso gorgonzola"],
    postBake: ["Miel trufada", "Cacahuete garrapiñado"],
  },
  {
    id: "iberica",
    type: "pizza",
    name: "Ibérica",
    image: "img/iberica.png",
    preBake: ["Salsa de tomate", "Mozzarella"],
    postBake: ["Paleta ibérica", "Queso manchego DOP", "Romero fresco"],
  },

  // Calzones
  {
    id: "calzone-napoletano",
    type: "calzone",
    name: "Calzone Napoletano",
    image: "img/calzone-napoletano.jpg", // si no existe, puedes cambiarlo o dejarlo
    preBake: ["Queso", "Carne de vacuno", "Jamón york", "Queso provolone (borde relleno)"],
    postBake: ["Salsa de tomate", "Parmesano", "Albahaca"],
  },
  {
    id: "calzone-chistorra-e-uovo",
    type: "calzone",
    name: "Calzone Chistorra e Uovo",
    image: "img/calzone-chistorra-e-uovo.jpg", // si no existe, puedes cambiarlo o dejarlo
    preBake: ["Jamón york", "Huevo a baja temperatura", "Crema de parmesano", "Chistorra (borde relleno)"],
    postBake: ["Pesto verde"],
  },
];
